# Generated by Django 2.1.5 on 2019-03-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='客户姓名')),
                ('age', models.IntegerField(verbose_name='客户年龄')),
                ('tel', models.CharField(max_length=11, verbose_name='客户电话')),
                ('email', models.EmailField(max_length=254, verbose_name='客户邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='支付金额')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='支付时间')),
                ('customer', models.ForeignKey(on_delete=True, to='web.Customer', verbose_name='支付客户')),
            ],
        ),
    ]
