# Generated by Django 2.1.5 on 2019-03-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190301_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.IntegerField(blank=True, verbose_name='用户电话'),
        ),
    ]
