# Generated by Django 2.1.5 on 2019-03-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20190301_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='', max_length=64, verbose_name='密码'),
        ),
    ]
