# Generated by Django 2.1.5 on 2019-03-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20190303_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='menus',
            field=models.ForeignKey(help_text='null表示非菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='一级菜单名称'),
        ),
    ]
