# Generated by Django 2.1.5 on 2019-03-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='URL别名'),
        ),
    ]
